.TH erl_docgen 7 "erl_docgen 0.3.5" "Ericsson AB" "Erlang Application Definition"
.SH NAME
erl_docgen \- 
    The erl_docgen application is used to produce the OTP documentation.
  
.SH DESCRIPTION
.LP
The application consists of the following parts 
.RS 2
.TP 2
.B
XSL:
A number of XSL files that is used to transform the xml files to html, pdf or man pages\&.
.TP 2
.B
DTDs:
The DTDs used for the OTP documentation\&.
.TP 2
.B
escripts:
Some scripts that is used to produce xml files according to OTP DTDs from some different input\&.
.TP 2
.B
misc:
Erlang logo, javascripts and css stylesheets used in the documentation\&.
.RE 