.TH crashdump_viewer 3 "observer 2.0" "Ericsson AB" "Erlang Module Definition"
.SH NAME
crashdump_viewer \- A WxWidgets based tool for browsing Erlang
  crashdumps.
.SH DESCRIPTION
.LP
The Crashdump Viewer is a WxWidgets based tool for browsing Erlang crashdumps\&.
.LP
See the \fBuser\&'s guide\fR\& for more information about how to get started with the Crashdump Viewer\&.
.SH EXPORTS
.LP
.B
start() -> ok
.br
.B
start(File) -> ok
.br
.RS
.LP
Types:

.RS 3
File = string()
.br
.RS 2
The file name of the crashdump\&.
.RE
.RE
.RE
.RS
.LP
This function starts the \fIcrashdump_viewer\fR\& GUI and loads the given crashdump\&.
.LP
If \fIFile\fR\& is not given, a file dialog will be opened where the crashdump can be selected\&.
.RE
.LP
.B
stop() -> ok
.br
.RS
.LP
This function stops the \fIcrashdump_viewer\fR\& and closes all GUI windows\&.
.RE