.TH observer 3 "observer 2.0" "Ericsson AB" "Erlang Module Definition"
.SH NAME
observer \- A GUI tool for observing an erlang system.
.SH DESCRIPTION
.LP
The observer is gui frontend containing various tools to inspect a system\&. It displays system information, application structures, process information, ets or mnesia tables and a frontend for tracing with \fBttb\fR\&\&.
.LP
See the \fBuser\&'s guide\fR\& for more information about how to get started\&.
.SH EXPORTS
.LP
.B
start() -> ok
.br
.RS
.LP
This function starts the \fIobserver\fR\& gui\&. Close the window to stop the application\&.
.RE