.TH wxArtProvider 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxArtProvider \- See external documentation: wxArtProvider.
.SH DESCRIPTION
.LP
See external documentation: wxArtProvider\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxArtProvider()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getBitmap(Id) -> wxBitmap() (see module wxBitmap)
.br
.RS
.LP
Types:

.RS 3
Id = chardata() (see module unicode)
.br
.RE
.RE
.RS
.LP
Equivalent to \fBgetBitmap(Id, [])\fR\&\&.
.RE
.LP
.B
getBitmap(Id, Option::[Option]) -> wxBitmap() (see module wxBitmap)
.br
.RS
.LP
Types:

.RS 3
Id = chardata() (see module unicode)
.br
Option = {client, chardata() (see module unicode)} | {size, {W::integer(), H::integer()}}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getIcon(Id) -> wxIcon() (see module wxIcon)
.br
.RS
.LP
Types:

.RS 3
Id = chardata() (see module unicode)
.br
.RE
.RE
.RS
.LP
Equivalent to \fBgetIcon(Id, [])\fR\&\&.
.RE
.LP
.B
getIcon(Id, Option::[Option]) -> wxIcon() (see module wxIcon)
.br
.RS
.LP
Types:

.RS 3
Id = chardata() (see module unicode)
.br
Option = {client, chardata() (see module unicode)} | {size, {W::integer(), H::integer()}}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>