.TH wxBrush 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxBrush \- See external documentation: wxBrush.
.SH DESCRIPTION
.LP
See external documentation: wxBrush\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxBrush()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxBrush()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Colour) -> wxBrush()
.br
.RS
.LP
Types:

.RS 3
Colour = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Also:
.br
new(StippleBitmap) -> wxBrush() when
.br
StippleBitmap::wxBitmap:wxBitmap()\&.
.br

.RE
.LP
.B
new(Colour, Option::[Option]) -> wxBrush()
.br
.RS
.LP
Types:

.RS 3
Colour = wx_colour() (see module wx)
.br
Option = {style, integer()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColour(This) -> wx_colour4() (see module wx)
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getStipple(This) -> wxBitmap() (see module wxBitmap)
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getStyle(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isHatch(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isOk(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This, Col) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
Col = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This, R, G, B) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
R = integer()
.br
G = integer()
.br
B = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setStipple(This, Stipple) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
Stipple = wxBitmap() (see module wxBitmap)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setStyle(This, Style) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxBrush()
.br
Style = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxBrush()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>