.TH wxCursor 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxCursor \- See external documentation: wxCursor.
.SH DESCRIPTION
.LP
See external documentation: wxCursor\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxBitmap\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxCursor()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxCursor()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(CursorId) -> wxCursor()
.br
.RS
.LP
Types:

.RS 3
CursorId = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Also:
.br
new(Image) -> wxCursor() when
.br
Image::wxImage:wxImage()\&.
.br

.RE
.LP
.B
new(Bits, Width, Height) -> wxCursor()
.br
.RS
.LP
Types:

.RS 3
Bits = binary()
.br
Width = integer()
.br
Height = integer()
.br
.RE
.RE
.RS
.LP
\fIThis function is deprecated: \fR\&deprecated function not available in wxWidgets-2\&.9 and later
.LP
Equivalent to \fBnew(Bits, Width, Height, [])\fR\&\&.
.RE
.LP
.B
new(Bits, Width, Height, Option::[Option]) -> wxCursor()
.br
.RS
.LP
Types:

.RS 3
Bits = binary()
.br
Width = integer()
.br
Height = integer()
.br
Option = {hotSpotX, integer()} | {hotSpotY, integer()}
.br
.RE
.RE
.RS
.LP
\fIThis function is deprecated: \fR\&deprecated function not available in wxWidgets-2\&.9 and later
.LP
See external documentation\&.
.RE
.LP
.B
ok(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxCursor()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxCursor()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>