.TH wxFilePickerCtrl 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxFilePickerCtrl \- See external documentation: wxFilePickerCtrl.
.SH DESCRIPTION
.LP
See external documentation: wxFilePickerCtrl\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxPickerBase\fR\& 
.br
\fBwxControl\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxFilePickerCtrl()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxFilePickerCtrl()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Parent, Id) -> wxFilePickerCtrl()
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow() (see module wxWindow)
.br
Id = integer()
.br
.RE
.RE
.RS
.LP
Equivalent to \fBnew(Parent, Id, [])\fR\&\&.
.RE
.LP
.B
new(Parent, Id, Option::[Option]) -> wxFilePickerCtrl()
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow() (see module wxWindow)
.br
Id = integer()
.br
Option = {path, chardata() (see module unicode)} | {message, chardata() (see module unicode)} | {wildcard, chardata() (see module unicode)} | {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()} | {validator, wx_object() (see module wx)}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This, Parent, Id) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxFilePickerCtrl()
.br
Parent = wxWindow() (see module wxWindow)
.br
Id = integer()
.br
.RE
.RE
.RS
.LP
Equivalent to \fBcreate(This, Parent, Id, [])\fR\&\&.
.RE
.LP
.B
create(This, Parent, Id, Option::[Option]) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxFilePickerCtrl()
.br
Parent = wxWindow() (see module wxWindow)
.br
Id = integer()
.br
Option = {path, chardata() (see module unicode)} | {message, chardata() (see module unicode)} | {wildcard, chardata() (see module unicode)} | {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()} | {validator, wx_object() (see module wx)}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPath(This) -> charlist() (see module unicode)
.br
.RS
.LP
Types:

.RS 3
This = wxFilePickerCtrl()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setPath(This, Str) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxFilePickerCtrl()
.br
Str = chardata() (see module unicode)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxFilePickerCtrl()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>