.TH wxGraphicsRenderer 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxGraphicsRenderer \- See external documentation: wxGraphicsRenderer.
.SH DESCRIPTION
.LP
See external documentation: wxGraphicsRenderer\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxGraphicsRenderer()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getDefaultRenderer() -> wxGraphicsRenderer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
createContext(This, Dc) -> wxGraphicsContext() (see module wxGraphicsContext)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
Dc = wxWindowDC() (see module wxWindowDC) | wxWindow() (see module wxWindow)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
createPen(This, Pen) -> wxGraphicsPen() (see module wxGraphicsPen)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
Pen = wxPen() (see module wxPen)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
createBrush(This, Brush) -> wxGraphicsBrush() (see module wxGraphicsBrush)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
Brush = wxBrush() (see module wxBrush)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
createLinearGradientBrush(This, X1, Y1, X2, Y2, C1, C2) -> wxGraphicsBrush() (see module wxGraphicsBrush)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
X1 = number()
.br
Y1 = number()
.br
X2 = number()
.br
Y2 = number()
.br
C1 = wx_colour() (see module wx)
.br
C2 = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
\fIThis function is deprecated: \fR\&deprecated function not available in wxWidgets-2\&.9 and later
.LP
See external documentation\&.
.RE
.LP
.B
createRadialGradientBrush(This, Xo, Yo, Xc, Yc, Radius, OColor, CColor) -> wxGraphicsBrush() (see module wxGraphicsBrush)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
Xo = number()
.br
Yo = number()
.br
Xc = number()
.br
Yc = number()
.br
Radius = number()
.br
OColor = wx_colour() (see module wx)
.br
CColor = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
\fIThis function is deprecated: \fR\&deprecated function not available in wxWidgets-2\&.9 and later
.LP
See external documentation\&.
.RE
.LP
.B
createFont(This, Font) -> wxGraphicsFont() (see module wxGraphicsFont)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
Font = wxFont() (see module wxFont)
.br
.RE
.RE
.RS
.LP
Equivalent to \fBcreateFont(This, Font, [])\fR\&\&.
.RE
.LP
.B
createFont(This, Font, Option::[Option]) -> wxGraphicsFont() (see module wxGraphicsFont)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
Font = wxFont() (see module wxFont)
.br
Option = {col, wx_colour() (see module wx)}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
createMatrix(This) -> wxGraphicsMatrix() (see module wxGraphicsMatrix)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
.RE
.RE
.RS
.LP
Equivalent to \fBcreateMatrix(This, [])\fR\&\&.
.RE
.LP
.B
createMatrix(This, Option::[Option]) -> wxGraphicsMatrix() (see module wxGraphicsMatrix)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
Option = {a, number()} | {b, number()} | {c, number()} | {d, number()} | {tx, number()} | {ty, number()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
createPath(This) -> wxGraphicsPath() (see module wxGraphicsPath)
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsRenderer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>