.TH wxIdleEvent 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxIdleEvent \- See external documentation: wxIdleEvent.
.SH DESCRIPTION
.LP
See external documentation: wxIdleEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fIidle\fR\&
.RE
.LP
See also the message variant \fB#wxIdle{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxIdleEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
canSend(Win) -> boolean()
.br
.RS
.LP
Types:

.RS 3
Win = wxWindow() (see module wxWindow)
.br
.RE
.RE
.RS
.LP
\fIThis function is deprecated: \fR\&deprecated function not available in wxWidgets-2\&.9 and later
.LP
See external documentation\&.
.RE
.LP
.B
getMode() -> wx_enum() (see module wx)
.br
.RS
.LP
See external documentation\&. 
.br
Res = ?wxIDLE_PROCESS_ALL | ?wxIDLE_PROCESS_SPECIFIED
.RE
.LP
.B
requestMore(This) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxIdleEvent()
.br
.RE
.RE
.RS
.LP
Equivalent to \fBrequestMore(This, [])\fR\&\&.
.RE
.LP
.B
requestMore(This, Option::[Option]) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxIdleEvent()
.br
Option = {needMore, boolean()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
moreRequested(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxIdleEvent()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setMode(Mode) -> ok
.br
.RS
.LP
Types:

.RS 3
Mode = wx_enum() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Mode = ?wxIDLE_PROCESS_ALL | ?wxIDLE_PROCESS_SPECIFIED
.RE
.SH AUTHORS
.LP

.I
<>