.TH wxListItem 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxListItem \- See external documentation: wxListItem.
.SH DESCRIPTION
.LP
See external documentation: wxListItem\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxListItem()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxListItem()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Item) -> wxListItem()
.br
.RS
.LP
Types:

.RS 3
Item = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
clear(This) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getAlign(This) -> wx_enum() (see module wx)
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Res = ?wxLIST_FORMAT_LEFT | ?wxLIST_FORMAT_RIGHT | ?wxLIST_FORMAT_CENTRE | ?wxLIST_FORMAT_CENTER
.RE
.LP
.B
getBackgroundColour(This) -> wx_colour4() (see module wx)
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColumn(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFont(This) -> wxFont() (see module wxFont)
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getId(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getImage(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getMask(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getState(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getText(This) -> charlist() (see module unicode)
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getTextColour(This) -> wx_colour4() (see module wx)
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getWidth(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setAlign(This, Align) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
Align = wx_enum() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Align = ?wxLIST_FORMAT_LEFT | ?wxLIST_FORMAT_RIGHT | ?wxLIST_FORMAT_CENTRE | ?wxLIST_FORMAT_CENTER
.RE
.LP
.B
setBackgroundColour(This, ColBack) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
ColBack = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColumn(This, Col) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
Col = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setFont(This, Font) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
Font = wxFont() (see module wxFont)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setId(This, Id) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
Id = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setImage(This, Image) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
Image = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setMask(This, Mask) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
Mask = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setState(This, State) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
State = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setStateMask(This, StateMask) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
StateMask = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setText(This, Text) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
Text = chardata() (see module unicode)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setTextColour(This, ColText) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
ColText = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setWidth(This, Width) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListItem()
.br
Width = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxListItem()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>