.TH wxListView 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxListView \- See external documentation: wxListView.
.SH DESCRIPTION
.LP
See external documentation: wxListView\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxControl\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxListView()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
clearColumnImage(This, Col) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
Col = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
focus(This, Index) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
Index = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFirstSelected(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFocusedItem(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getNextSelected(This, Item) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
Item = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isSelected(This, Index) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
Index = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
select(This, N) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
N = integer()
.br
.RE
.RE
.RS
.LP
Equivalent to \fBselect(This, N, [])\fR\&\&.
.RE
.LP
.B
select(This, N, Option::[Option]) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
N = integer()
.br
Option = {on, boolean()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColumnImage(This, Col, Image) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxListView()
.br
Col = integer()
.br
Image = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>