.TH wxMask 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxMask \- See external documentation: wxMask.
.SH DESCRIPTION
.LP
See external documentation: wxMask\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxMask()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxMask()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Bitmap) -> wxMask()
.br
.RS
.LP
Types:

.RS 3
Bitmap = wxBitmap() (see module wxBitmap)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Bitmap, PaletteIndex) -> wxMask()
.br
.RS
.LP
Types:

.RS 3
Bitmap = wxBitmap() (see module wxBitmap)
.br
PaletteIndex = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Also:
.br
new(Bitmap, Colour) -> wxMask() when
.br
Bitmap::wxBitmap:wxBitmap(), Colour::wx:wx_colour()\&.
.br

.RE
.LP
.B
create(This, Bitmap) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxMask()
.br
Bitmap = wxBitmap() (see module wxBitmap)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This, Bitmap, PaletteIndex) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxMask()
.br
Bitmap = wxBitmap() (see module wxBitmap)
.br
PaletteIndex = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Also:
.br
create(This, Bitmap, Colour) -> boolean() when
.br
This::wxMask(), Bitmap::wxBitmap:wxBitmap(), Colour::wx:wx_colour()\&.
.br

.RE
.LP
.B
destroy(This::wxMask()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>