.TH wxPen 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxPen \- See external documentation: wxPen.
.SH DESCRIPTION
.LP
See external documentation: wxPen\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxPen()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxPen()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Colour) -> wxPen()
.br
.RS
.LP
Types:

.RS 3
Colour = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
Equivalent to \fBnew(Colour, [])\fR\&\&.
.RE
.LP
.B
new(Colour, Option::[Option]) -> wxPen()
.br
.RS
.LP
Types:

.RS 3
Colour = wx_colour() (see module wx)
.br
Option = {width, integer()} | {style, integer()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getCap(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColour(This) -> wx_colour4() (see module wx)
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getJoin(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getStyle(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getWidth(This) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isOk(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setCap(This, CapStyle) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
CapStyle = wx_enum() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
CapStyle = integer
.RE
.LP
.B
setColour(This, Colour) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
Colour = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This, Red, Green, Blue) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
Red = integer()
.br
Green = integer()
.br
Blue = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setJoin(This, JoinStyle) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
JoinStyle = wx_enum() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
JoinStyle = integer
.RE
.LP
.B
setStyle(This, Style) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
Style = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setWidth(This, Width) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxPen()
.br
Width = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxPen()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>