.TH wxSashLayoutWindow 3 "wx 1.2" "" "Erlang Module Definition"
.SH NAME
wxSashLayoutWindow \- See external documentation: wxSashLayoutWindow.
.SH DESCRIPTION
.LP
See external documentation: wxSashLayoutWindow\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxSashWindow\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxSashLayoutWindow()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxSashLayoutWindow()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Parent) -> wxSashLayoutWindow()
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow() (see module wxWindow)
.br
.RE
.RE
.RS
.LP
Equivalent to \fBnew(Parent, [])\fR\&\&.
.RE
.LP
.B
new(Parent, Option::[Option]) -> wxSashLayoutWindow()
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow() (see module wxWindow)
.br
Option = {id, integer()} | {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This, Parent) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxSashLayoutWindow()
.br
Parent = wxWindow() (see module wxWindow)
.br
.RE
.RE
.RS
.LP
Equivalent to \fBcreate(This, Parent, [])\fR\&\&.
.RE
.LP
.B
create(This, Parent, Option::[Option]) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxSashLayoutWindow()
.br
Parent = wxWindow() (see module wxWindow)
.br
Option = {id, integer()} | {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getAlignment(This) -> wx_enum() (see module wx)
.br
.RS
.LP
Types:

.RS 3
This = wxSashLayoutWindow()
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Res = ?wxLAYOUT_NONE | ?wxLAYOUT_TOP | ?wxLAYOUT_LEFT | ?wxLAYOUT_RIGHT | ?wxLAYOUT_BOTTOM
.RE
.LP
.B
getOrientation(This) -> wx_enum() (see module wx)
.br
.RS
.LP
Types:

.RS 3
This = wxSashLayoutWindow()
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Res = ?wxLAYOUT_HORIZONTAL | ?wxLAYOUT_VERTICAL
.RE
.LP
.B
setAlignment(This, Align) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxSashLayoutWindow()
.br
Align = wx_enum() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Align = ?wxLAYOUT_NONE | ?wxLAYOUT_TOP | ?wxLAYOUT_LEFT | ?wxLAYOUT_RIGHT | ?wxLAYOUT_BOTTOM
.RE
.LP
.B
setDefaultSize(This, Size) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxSashLayoutWindow()
.br
Size = {W::integer(), H::integer()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setOrientation(This, Orient) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxSashLayoutWindow()
.br
Orient = wx_enum() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Orient = ?wxLAYOUT_HORIZONTAL | ?wxLAYOUT_VERTICAL
.RE
.LP
.B
destroy(This::wxSashLayoutWindow()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>