.TH cdv 1 "observer 2.0" "Ericsson AB" "User Commands"
.SH NAME
cdv \- Script used for starting the Crashdump Viewer from the
  OS command line.
  
.SH DESCRIPTION
.LP
The \fIcdv\fR\& shell script can be found under the \fIpriv\fR\& directory of the \fIobserver\fR\& application\&. The script is used for starting the Crashdump Viewer tool from the OS command line\&.
.LP
For Windows users, \fIcdv\&.bat\fR\& can be found in the same location\&.
.SH EXPORTS
.LP
.B
cdv [file]
.br
.RS
.LP
The \fIfile\fR\& arguments is optional\&. If not given, a file dialog will pop up allowing the user to select a crashdump from the file system\&.
.RE